Default: &defaults
  database: bitidx.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: bitidx_test.sqlite3
  <<: *defaults

Staging:
  database: bitidx_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: bitidx_production.sqlite3
  poolsize: 100
  <<: *defaults
